# Generated by Django 5.1.4 on 2025-01-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TERMS_OF_SERVICE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default=None, max_length=50, verbose_name="Название"
                    ),
                ),
                ("text", models.TextField(verbose_name="Описание")),
            ],
        ),
    ]
