# Generated by Django 5.1.4 on 2025-01-26 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_customer_user_subscription_alter_user_plan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="plan",
        ),
    ]
