# Generated by Django 5.1.4 on 2025-02-11 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_user_stripe_customer_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="stripe_customer_id",
        ),
    ]
