# Generated by Django 5.1.4 on 2025-02-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_remove_user_stripe_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sub_status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
