# Generated by Django 5.1.4 on 2025-01-13 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("link", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="link",
            name="category",
        ),
        migrations.RemoveField(
            model_name="link",
            name="created_by",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Link",
        ),
    ]
