# Generated by Django 5.1.4 on 2025-02-09 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("link", "0004_alter_category_options_alter_link_options"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("name",)},
        ),
    ]
